<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="0" failed="6" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-07-26T19:04:03Z" name="Login tests" finished-at="2019-07-26T19:04:03Z" duration-ms="31">
    <groups>
    </groups>
    <test started-at="2019-07-26T19:04:03Z" name="Success Login" finished-at="2019-07-26T19:04:03Z" duration-ms="28">
      <class name="tests.LoginTest">
        <test-method signature="testUserIsAbleToLoginIntoApp()[pri:0, instance:tests.LoginTest@6c80d78a]" started-at="2019-07-26T19:04:03Z" name="testUserIsAbleToLoginIntoApp" finished-at="2019-07-26T19:04:03Z" duration-ms="5" status="FAIL">
          <exception class="java.lang.IllegalStateException">
            <message>
              <![CDATA[You cannot  start the site on macOS]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalStateException: You cannot  start the site on macOS
at tests.GenericTest.getBrowser(GenericTest.java:69)
at tests.GenericTest.getDriver(GenericTest.java:110)
at tests.GenericTest.openLoginPage(GenericTest.java:119)
at tests.LoginTest.testUserIsAbleToLoginIntoApp(LoginTest.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalStateException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUserIsAbleToLoginIntoApp -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:tests.LoginTest@6c80d78a]" started-at="2019-07-26T19:04:03Z" name="closeBrowser" finished-at="2019-07-26T19:04:03Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- tests.LoginTest -->
    </test> <!-- Success Login -->
    <test started-at="2019-07-26T19:04:03Z" name="Login_Negative scenarios" finished-at="2019-07-26T19:04:03Z" duration-ms="31">
      <class name="tests.LoginTestNegative_2">
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:tests.LoginTestNegative_2@52bf72b5]" started-at="2019-07-26T19:04:03Z" name="closeBrowser" finished-at="2019-07-26T19:04:03Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method signature="testUserIsNotAbleToLoginWithoutPassword()[pri:0, instance:tests.LoginTestNegative_2@52bf72b5]" started-at="2019-07-26T19:04:03Z" name="testUserIsNotAbleToLoginWithoutPassword" finished-at="2019-07-26T19:04:03Z" duration-ms="0" status="FAIL">
          <exception class="java.lang.IllegalStateException">
            <message>
              <![CDATA[You cannot  start the site on macOS]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalStateException: You cannot  start the site on macOS
at tests.GenericTest.getBrowser(GenericTest.java:69)
at tests.GenericTest.getDriver(GenericTest.java:110)
at tests.GenericTest.openLoginPage(GenericTest.java:119)
at tests.LoginTestNegative_2.testUserIsNotAbleToLoginWithoutPassword(LoginTestNegative_2.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalStateException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUserIsNotAbleToLoginWithoutPassword -->
      </class> <!-- tests.LoginTestNegative_2 -->
      <class name="tests.LoginTestNegative_3">
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:tests.LoginTestNegative_3@37afeb11]" started-at="2019-07-26T19:04:03Z" name="closeBrowser" finished-at="2019-07-26T19:04:03Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method signature="testUserIsNotAbleToLoginWithoutUsername()[pri:0, instance:tests.LoginTestNegative_3@37afeb11]" started-at="2019-07-26T19:04:03Z" name="testUserIsNotAbleToLoginWithoutUsername" finished-at="2019-07-26T19:04:03Z" duration-ms="0" status="FAIL">
          <exception class="java.lang.IllegalStateException">
            <message>
              <![CDATA[You cannot  start the site on macOS]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalStateException: You cannot  start the site on macOS
at tests.GenericTest.getBrowser(GenericTest.java:69)
at tests.GenericTest.getDriver(GenericTest.java:110)
at tests.GenericTest.openLoginPage(GenericTest.java:119)
at tests.LoginTestNegative_3.testUserIsNotAbleToLoginWithoutUsername(LoginTestNegative_3.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalStateException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUserIsNotAbleToLoginWithoutUsername -->
      </class> <!-- tests.LoginTestNegative_3 -->
      <class name="tests.LoginTestNegative_1">
        <test-method signature="testUserIsNotAbleToLoginWithoutUsernameAndPassword()[pri:0, instance:tests.LoginTestNegative_1@6d763516]" started-at="2019-07-26T19:04:03Z" name="testUserIsNotAbleToLoginWithoutUsernameAndPassword" finished-at="2019-07-26T19:04:03Z" duration-ms="5" status="FAIL">
          <exception class="java.lang.IllegalStateException">
            <message>
              <![CDATA[You cannot  start the site on macOS]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalStateException: You cannot  start the site on macOS
at tests.GenericTest.getBrowser(GenericTest.java:69)
at tests.GenericTest.getDriver(GenericTest.java:110)
at tests.GenericTest.openLoginPage(GenericTest.java:119)
at tests.LoginTestNegative_1.testUserIsNotAbleToLoginWithoutUsernameAndPassword(LoginTestNegative_1.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalStateException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUserIsNotAbleToLoginWithoutUsernameAndPassword -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:tests.LoginTestNegative_1@6d763516]" started-at="2019-07-26T19:04:03Z" name="closeBrowser" finished-at="2019-07-26T19:04:03Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- tests.LoginTestNegative_1 -->
      <class name="tests.LoginTestNegative_4">
        <test-method signature="testLockedUserIsNotAbleToLogin()[pri:0, instance:tests.LoginTestNegative_4@515aebb0]" started-at="2019-07-26T19:04:03Z" name="testLockedUserIsNotAbleToLogin" finished-at="2019-07-26T19:04:03Z" duration-ms="0" status="FAIL">
          <exception class="java.lang.IllegalStateException">
            <message>
              <![CDATA[You cannot  start the site on macOS]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalStateException: You cannot  start the site on macOS
at tests.GenericTest.getBrowser(GenericTest.java:69)
at tests.GenericTest.getDriver(GenericTest.java:110)
at tests.GenericTest.openLoginPage(GenericTest.java:119)
at tests.LoginTestNegative_4.testLockedUserIsNotAbleToLogin(LoginTestNegative_4.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalStateException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLockedUserIsNotAbleToLogin -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:tests.LoginTestNegative_4@515aebb0]" started-at="2019-07-26T19:04:03Z" name="closeBrowser" finished-at="2019-07-26T19:04:03Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- tests.LoginTestNegative_4 -->
      <class name="tests.LoginTestNegative_5">
        <test-method signature="testUserIsNotAbleToLoginIntoAppWithWrongCredentials()[pri:0, instance:tests.LoginTestNegative_5@dd8ba08]" started-at="2019-07-26T19:04:03Z" name="testUserIsNotAbleToLoginIntoAppWithWrongCredentials" finished-at="2019-07-26T19:04:03Z" duration-ms="0" status="FAIL">
          <exception class="java.lang.IllegalStateException">
            <message>
              <![CDATA[You cannot  start the site on macOS]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalStateException: You cannot  start the site on macOS
at tests.GenericTest.getBrowser(GenericTest.java:69)
at tests.GenericTest.getDriver(GenericTest.java:110)
at tests.GenericTest.openLoginPage(GenericTest.java:119)
at tests.LoginTestNegative_5.testUserIsNotAbleToLoginIntoAppWithWrongCredentials(LoginTestNegative_5.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalStateException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUserIsNotAbleToLoginIntoAppWithWrongCredentials -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:tests.LoginTestNegative_5@dd8ba08]" started-at="2019-07-26T19:04:03Z" name="closeBrowser" finished-at="2019-07-26T19:04:03Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- tests.LoginTestNegative_5 -->
    </test> <!-- Login_Negative scenarios -->
  </suite> <!-- Login tests -->
</testng-results>
